### ISSUE TITLE
[Feature Request]: Mobile-friendly / Responsive design required

### ISSUE THREAD

**Issue by dmotts** [Alitindrawan24/nuxt-pokedex#16]
A mobile-friendly design would greatly improve the user experience for mobile users.

**Comment by dmotts** [comment]
Hold the 📱 @Alitindrawan24 I would love to but, unfortunately I won't be able to fit this in my schedule. 

I appreciate your offer and  I'm sure someone else will gladly take this task very soon!

**Comment by Alitindrawan24** [comment]
@dmotts sure no problem

**Comment by Khusyasy** [comment]
Hello @Alitindrawan24, I would love to help with this issue, can you please assign me?

Also, for the mobile-friendly part, because the website already have responsive table, maybe I should just fix the design for the filter part above the table, and maybe other buttons as well?

![image](https://github.com/user-attachments/assets/0140c9e0-9c93-4f0d-86cd-6549e2944b40)

**Comment by Alitindrawan24** [comment]
@Khusyasy interesting, already assigned to you
